// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `myinterface.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.sun.ice.demo.myinter;

public abstract class Callback_MyInterface_getName
    extends IceInternal.TwowayCallback implements Ice.TwowayCallbackArg1UE<String>
{
    public final void __completed(Ice.AsyncResult __result)
    {
        MyInterfacePrxHelper.__getName_completed(this, __result);
    }
}
