// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `myinterface.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.sun.ice.demo.myinter;

public interface MyInterface3 extends Ice.Object,
                                      _MyInterface3Operations, _MyInterface3OperationsNC,
                                      StudentInterface,
                                      MyInterface
{
    public static final String ice_staticId = "::myinter::MyInterface3";

    public static final long serialVersionUID = 556419966L;
}
