// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `myinterface.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.sun.ice.demo.myinter;

public interface StudentInterfacePrx extends Ice.ObjectPrx
{
    public MyInterfacePrx getMyInterface()
        throws com.sun.ice.demo.common.ProxyException;

    public MyInterfacePrx getMyInterface(java.util.Map<String, String> __ctx)
        throws com.sun.ice.demo.common.ProxyException;

    public Ice.AsyncResult begin_getMyInterface();

    public Ice.AsyncResult begin_getMyInterface(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getMyInterface(Ice.Callback __cb);

    public Ice.AsyncResult begin_getMyInterface(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getMyInterface(Callback_StudentInterface_getMyInterface __cb);

    public Ice.AsyncResult begin_getMyInterface(java.util.Map<String, String> __ctx, Callback_StudentInterface_getMyInterface __cb);

    public Ice.AsyncResult begin_getMyInterface(IceInternal.Functional_GenericCallback1<MyInterfacePrx> __responseCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.UserException> __userExceptionCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getMyInterface(IceInternal.Functional_GenericCallback1<MyInterfacePrx> __responseCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.UserException> __userExceptionCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_getMyInterface(java.util.Map<String, String> __ctx, 
                                                IceInternal.Functional_GenericCallback1<MyInterfacePrx> __responseCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.UserException> __userExceptionCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getMyInterface(java.util.Map<String, String> __ctx, 
                                                IceInternal.Functional_GenericCallback1<MyInterfacePrx> __responseCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.UserException> __userExceptionCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                IceInternal.Functional_BoolCallback __sentCb);

    public MyInterfacePrx end_getMyInterface(Ice.AsyncResult __result)
        throws com.sun.ice.demo.common.ProxyException;

    public void setMyInterface(MyInterfacePrx myInterface)
        throws com.sun.ice.demo.common.ProxyException;

    public void setMyInterface(MyInterfacePrx myInterface, java.util.Map<String, String> __ctx)
        throws com.sun.ice.demo.common.ProxyException;

    public Ice.AsyncResult begin_setMyInterface(MyInterfacePrx myInterface);

    public Ice.AsyncResult begin_setMyInterface(MyInterfacePrx myInterface, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_setMyInterface(MyInterfacePrx myInterface, Ice.Callback __cb);

    public Ice.AsyncResult begin_setMyInterface(MyInterfacePrx myInterface, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_setMyInterface(MyInterfacePrx myInterface, Callback_StudentInterface_setMyInterface __cb);

    public Ice.AsyncResult begin_setMyInterface(MyInterfacePrx myInterface, java.util.Map<String, String> __ctx, Callback_StudentInterface_setMyInterface __cb);

    public Ice.AsyncResult begin_setMyInterface(MyInterfacePrx myInterface, 
                                                IceInternal.Functional_VoidCallback __responseCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.UserException> __userExceptionCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_setMyInterface(MyInterfacePrx myInterface, 
                                                IceInternal.Functional_VoidCallback __responseCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.UserException> __userExceptionCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_setMyInterface(MyInterfacePrx myInterface, 
                                                java.util.Map<String, String> __ctx, 
                                                IceInternal.Functional_VoidCallback __responseCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.UserException> __userExceptionCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_setMyInterface(MyInterfacePrx myInterface, 
                                                java.util.Map<String, String> __ctx, 
                                                IceInternal.Functional_VoidCallback __responseCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.UserException> __userExceptionCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                IceInternal.Functional_BoolCallback __sentCb);

    public void end_setMyInterface(Ice.AsyncResult __result)
        throws com.sun.ice.demo.common.ProxyException;
}
