// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `common.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.sun.ice.demo.common;

public class IllegProxyException extends ProxyException
{
    public IllegProxyException()
    {
        super();
        noParams = NoParams.ONE;
    }

    public IllegProxyException(Throwable __cause)
    {
        super(__cause);
        noParams = NoParams.ONE;
    }

    public IllegProxyException(String reason, int code, NoParams noParams)
    {
        super(reason);
        this.code = code;
        this.noParams = noParams;
    }

    public IllegProxyException(String reason, int code, NoParams noParams, Throwable __cause)
    {
        super(reason, __cause);
        this.code = code;
        this.noParams = noParams;
    }

    public String
    ice_name()
    {
        return "common::IllegProxyException";
    }

    public int code;

    public NoParams noParams;

    protected void
    __writeImpl(IceInternal.BasicStream __os)
    {
        __os.startWriteSlice("::common::IllegProxyException", -1, false);
        __os.writeInt(code);
        NoParams.__write(__os, noParams);
        __os.endWriteSlice();
        super.__writeImpl(__os);
    }

    protected void
    __readImpl(IceInternal.BasicStream __is)
    {
        __is.startReadSlice();
        code = __is.readInt();
        noParams = NoParams.__read(__is);
        __is.endReadSlice();
        super.__readImpl(__is);
    }

    public static final long serialVersionUID = 1718430054L;
}
