// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `common.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.sun.ice.demo.common;

public enum NoParams implements java.io.Serializable
{
    
    ONE(0),
    
    TWO(1);

    public int
    value()
    {
        return __value;
    }

    public static NoParams
    valueOf(int __v)
    {
        switch(__v)
        {
        case 0:
            return ONE;
        case 1:
            return TWO;
        }
        return null;
    }

    private
    NoParams(int __v)
    {
        __value = __v;
    }

    public void
    __write(IceInternal.BasicStream __os)
    {
        __os.writeEnum(value(), 1);
    }

    public static void
    __write(IceInternal.BasicStream __os, NoParams __v)
    {
        if(__v == null)
        {
            __os.writeEnum(com.sun.ice.demo.common.NoParams.ONE.value(), 1);
        }
        else
        {
            __os.writeEnum(__v.value(), 1);
        }
    }

    public static NoParams
    __read(IceInternal.BasicStream __is)
    {
        int __v = __is.readEnum(1);
        return __validate(__v);
    }

    private static NoParams
    __validate(int __v)
    {
        final NoParams __e = valueOf(__v);
        if(__e == null)
        {
            throw new Ice.MarshalException("enumerator value " + __v + " is out of range");
        }
        return __e;
    }

    private final int __value;
}
