// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `common.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.sun.ice.demo.common;

public class Student implements java.lang.Cloneable, java.io.Serializable
{
    public short age;

    public short
    getAge()
    {
        return age;
    }

    public void
    setAge(short _age)
    {
        age = _age;
    }

    public int height;

    public int
    getHeight()
    {
        return height;
    }

    public void
    setHeight(int _height)
    {
        height = _height;
    }

    public long legLength;

    public long
    getLegLength()
    {
        return legLength;
    }

    public void
    setLegLength(long _legLength)
    {
        legLength = _legLength;
    }

    public double money;

    public double
    getMoney()
    {
        return money;
    }

    public void
    setMoney(double _money)
    {
        money = _money;
    }

    public String name;

    public String
    getName()
    {
        return name;
    }

    public void
    setName(String _name)
    {
        name = _name;
    }

    public Books books;

    public Books
    getBooks()
    {
        return books;
    }

    public void
    setBooks(Books _books)
    {
        books = _books;
    }

    public Student()
    {
        name = "";
        books = new Books();
    }

    public Student(short age, int height, long legLength, double money, String name, Books books)
    {
        this.age = age;
        this.height = height;
        this.legLength = legLength;
        this.money = money;
        this.name = name;
        this.books = books;
    }

    public boolean
    equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        Student _r = null;
        if(rhs instanceof Student)
        {
            _r = (Student)rhs;
        }

        if(_r != null)
        {
            if(age != _r.age)
            {
                return false;
            }
            if(height != _r.height)
            {
                return false;
            }
            if(legLength != _r.legLength)
            {
                return false;
            }
            if(money != _r.money)
            {
                return false;
            }
            if(name != _r.name)
            {
                if(name == null || _r.name == null || !name.equals(_r.name))
                {
                    return false;
                }
            }
            if(books != _r.books)
            {
                if(books == null || _r.books == null || !books.equals(_r.books))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int
    hashCode()
    {
        int __h = 5381;
        __h = IceInternal.HashUtil.hashAdd(__h, "::common::Student");
        __h = IceInternal.HashUtil.hashAdd(__h, age);
        __h = IceInternal.HashUtil.hashAdd(__h, height);
        __h = IceInternal.HashUtil.hashAdd(__h, legLength);
        __h = IceInternal.HashUtil.hashAdd(__h, money);
        __h = IceInternal.HashUtil.hashAdd(__h, name);
        __h = IceInternal.HashUtil.hashAdd(__h, books);
        return __h;
    }

    public Student
    clone()
    {
        Student c = null;
        try
        {
            c = (Student)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void
    __write(IceInternal.BasicStream __os)
    {
        __os.writeShort(age);
        __os.writeInt(height);
        __os.writeLong(legLength);
        __os.writeDouble(money);
        __os.writeString(name);
        Books.__write(__os, books);
    }

    public void
    __read(IceInternal.BasicStream __is)
    {
        age = __is.readShort();
        height = __is.readInt();
        legLength = __is.readLong();
        money = __is.readDouble();
        name = __is.readString();
        books = Books.__read(__is, books);
    }

    static public void
    __write(IceInternal.BasicStream __os, Student __v)
    {
        if(__v == null)
        {
            __nullMarshalValue.__write(__os);
        }
        else
        {
            __v.__write(__os);
        }
    }

    static public Student
    __read(IceInternal.BasicStream __is, Student __v)
    {
        if(__v == null)
        {
             __v = new Student();
        }
        __v.__read(__is);
        return __v;
    }
    
    private static final Student __nullMarshalValue = new Student();

    public static final long serialVersionUID = 463209804L;
}
