// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `common.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.sun.ice.demo.common;

public final class StuListHelper
{
    public static void
    write(IceInternal.BasicStream __os, Student[] __v)
    {
        if(__v == null)
        {
            __os.writeSize(0);
        }
        else
        {
            __os.writeSize(__v.length);
            for(int __i0 = 0; __i0 < __v.length; __i0++)
            {
                Student.__write(__os, __v[__i0]);
            }
        }
    }

    public static Student[]
    read(IceInternal.BasicStream __is)
    {
        Student[] __v;
        final int __len0 = __is.readAndCheckSeqSize(28);
        __v = new Student[__len0];
        for(int __i0 = 0; __i0 < __len0; __i0++)
        {
            __v[__i0] = Student.__read(__is, __v[__i0]);
        }
        return __v;
    }
}
