// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `common.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.sun.ice.demo.common;

public final class StuListHolder extends Ice.Holder<Student[]>
{
    public
    StuListHolder()
    {
    }

    public
    StuListHolder(Student[] value)
    {
        super(value);
    }
}
