// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `common.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.sun.ice.demo.common;

public final class StuMapHelper
{
    public static void
    write(IceInternal.BasicStream __os, java.util.Map<java.lang.String, Student> __v)
    {
        if(__v == null)
        {
            __os.writeSize(0);
        }
        else
        {
            __os.writeSize(__v.size());
            for(java.util.Map.Entry<java.lang.String, Student> __e : __v.entrySet())
            {
                __os.writeString(__e.getKey());
                Student.__write(__os, __e.getValue());
            }
        }
    }

    public static java.util.Map<java.lang.String, Student>
    read(IceInternal.BasicStream __is)
    {
        java.util.Map<java.lang.String, Student> __v;
        __v = new java.util.HashMap<java.lang.String, com.sun.ice.demo.common.Student>();
        int __sz0 = __is.readSize();
        for(int __i0 = 0; __i0 < __sz0; __i0++)
        {
            String __key;
            __key = __is.readString();
            Student __value = null;
            __value = Student.__read(__is, __value);
            __v.put(__key, __value);
        }
        return __v;
    }
}
