// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `mymodule.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.sun.ice.demo.mymodule.module02;

public interface ModuleInterface extends Ice.Object,
                                         _ModuleInterfaceOperations, _ModuleInterfaceOperationsNC
{
    public static final String ice_staticId = "::mymodule::module02::ModuleInterface";

    public static final long serialVersionUID = -1945998124L;
}
