// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `myclass.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.sun.ice.demo.myclass;

public interface BaseInterfacePrx extends Ice.ObjectPrx
{
    public void sayHello();

    public void sayHello(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_sayHello();

    public Ice.AsyncResult begin_sayHello(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_sayHello(Ice.Callback __cb);

    public Ice.AsyncResult begin_sayHello(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_sayHello(Callback_BaseInterface_sayHello __cb);

    public Ice.AsyncResult begin_sayHello(java.util.Map<String, String> __ctx, Callback_BaseInterface_sayHello __cb);

    public Ice.AsyncResult begin_sayHello(IceInternal.Functional_VoidCallback __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_sayHello(IceInternal.Functional_VoidCallback __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                          IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_sayHello(java.util.Map<String, String> __ctx, 
                                          IceInternal.Functional_VoidCallback __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_sayHello(java.util.Map<String, String> __ctx, 
                                          IceInternal.Functional_VoidCallback __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                          IceInternal.Functional_BoolCallback __sentCb);

    public void end_sayHello(Ice.AsyncResult __result);
}
