// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `myclass.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.sun.ice.demo.myclass;

/**
 * Provides type-specific helper functions.
 **/
public final class ExtendInterfaceClassaPrxHelper extends Ice.ObjectPrxHelperBase implements ExtendInterfaceClassaPrx
{
    private static final String __sayHello_name = "sayHello";

    public void sayHello()
    {
        sayHello(null, false);
    }

    public void sayHello(java.util.Map<String, String> __ctx)
    {
        sayHello(__ctx, true);
    }

    private void sayHello(java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        end_sayHello(begin_sayHello(__ctx, __explicitCtx, true, null));
    }

    public Ice.AsyncResult begin_sayHello()
    {
        return begin_sayHello(null, false, false, null);
    }

    public Ice.AsyncResult begin_sayHello(java.util.Map<String, String> __ctx)
    {
        return begin_sayHello(__ctx, true, false, null);
    }

    public Ice.AsyncResult begin_sayHello(Ice.Callback __cb)
    {
        return begin_sayHello(null, false, false, __cb);
    }

    public Ice.AsyncResult begin_sayHello(java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_sayHello(__ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_sayHello(Callback_BaseInterface_sayHello __cb)
    {
        return begin_sayHello(null, false, false, __cb);
    }

    public Ice.AsyncResult begin_sayHello(java.util.Map<String, String> __ctx, Callback_BaseInterface_sayHello __cb)
    {
        return begin_sayHello(__ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_sayHello(IceInternal.Functional_VoidCallback __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_sayHello(null, false, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_sayHello(IceInternal.Functional_VoidCallback __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                          IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_sayHello(null, false, false, __responseCb, __exceptionCb, __sentCb);
    }

    public Ice.AsyncResult begin_sayHello(java.util.Map<String, String> __ctx, 
                                          IceInternal.Functional_VoidCallback __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_sayHello(__ctx, true, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_sayHello(java.util.Map<String, String> __ctx, 
                                          IceInternal.Functional_VoidCallback __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                          IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_sayHello(__ctx, true, false, __responseCb, __exceptionCb, __sentCb);
    }

    private Ice.AsyncResult begin_sayHello(java.util.Map<String, String> __ctx, 
                                           boolean __explicitCtx, 
                                           boolean __synchronous, 
                                           IceInternal.Functional_VoidCallback __responseCb, 
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                           IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_sayHello(__ctx, 
                              __explicitCtx, 
                              __synchronous, 
                              new IceInternal.Functional_OnewayCallback(__responseCb, __exceptionCb, __sentCb));
    }

    private Ice.AsyncResult begin_sayHello(java.util.Map<String, String> __ctx, 
                                           boolean __explicitCtx, 
                                           boolean __synchronous, 
                                           IceInternal.CallbackBase __cb)
    {
        IceInternal.OutgoingAsync __result = getOutgoingAsync(__sayHello_name, __cb);
        try
        {
            __result.prepare(__sayHello_name, Ice.OperationMode.Normal, __ctx, __explicitCtx, __synchronous);
            __result.writeEmptyParams();
            __result.invoke();
        }
        catch(Ice.Exception __ex)
        {
            __result.abort(__ex);
        }
        return __result;
    }

    public void end_sayHello(Ice.AsyncResult __iresult)
    {
        __end(__iresult, __sayHello_name);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static ExtendInterfaceClassaPrx checkedCast(Ice.ObjectPrx __obj)
    {
        return checkedCastImpl(__obj, ice_staticId(), ExtendInterfaceClassaPrx.class, ExtendInterfaceClassaPrxHelper.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @param __ctx The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static ExtendInterfaceClassaPrx checkedCast(Ice.ObjectPrx __obj, java.util.Map<String, String> __ctx)
    {
        return checkedCastImpl(__obj, __ctx, ice_staticId(), ExtendInterfaceClassaPrx.class, ExtendInterfaceClassaPrxHelper.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @param __facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static ExtendInterfaceClassaPrx checkedCast(Ice.ObjectPrx __obj, String __facet)
    {
        return checkedCastImpl(__obj, __facet, ice_staticId(), ExtendInterfaceClassaPrx.class, ExtendInterfaceClassaPrxHelper.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @param __facet The name of the desired facet.
     * @param __ctx The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static ExtendInterfaceClassaPrx checkedCast(Ice.ObjectPrx __obj, String __facet, java.util.Map<String, String> __ctx)
    {
        return checkedCastImpl(__obj, __facet, __ctx, ice_staticId(), ExtendInterfaceClassaPrx.class, ExtendInterfaceClassaPrxHelper.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param __obj The untyped proxy.
     * @return A proxy for this type.
     **/
    public static ExtendInterfaceClassaPrx uncheckedCast(Ice.ObjectPrx __obj)
    {
        return uncheckedCastImpl(__obj, ExtendInterfaceClassaPrx.class, ExtendInterfaceClassaPrxHelper.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param __obj The untyped proxy.
     * @param __facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    public static ExtendInterfaceClassaPrx uncheckedCast(Ice.ObjectPrx __obj, String __facet)
    {
        return uncheckedCastImpl(__obj, __facet, ExtendInterfaceClassaPrx.class, ExtendInterfaceClassaPrxHelper.class);
    }

    public static final String[] __ids =
    {
        "::Ice::Object",
        "::myclass::BaseInterface",
        "::myclass::ExtendInterfaceClassa"
    };

    /**
     * Provides the Slice type ID of this type.
     * @return The Slice type ID.
     **/
    public static String ice_staticId()
    {
        return __ids[2];
    }

    public static void __write(IceInternal.BasicStream __os, ExtendInterfaceClassaPrx v)
    {
        __os.writeProxy(v);
    }

    public static ExtendInterfaceClassaPrx __read(IceInternal.BasicStream __is)
    {
        Ice.ObjectPrx proxy = __is.readProxy();
        if(proxy != null)
        {
            ExtendInterfaceClassaPrxHelper result = new ExtendInterfaceClassaPrxHelper();
            result.__copyFrom(proxy);
            return result;
        }
        return null;
    }

    public static final long serialVersionUID = 0L;
}
