// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `myclass.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.sun.ice.demo.myclass;

public final class ExtendsClassHolder extends Ice.ObjectHolderBase<ExtendsClass>
{
    public
    ExtendsClassHolder()
    {
    }

    public
    ExtendsClassHolder(ExtendsClass value)
    {
        this.value = value;
    }

    public void
    patch(Ice.Object v)
    {
        if(v == null || v instanceof ExtendsClass)
        {
            value = (ExtendsClass)v;
        }
        else
        {
            IceInternal.Ex.throwUOE(type(), v);
        }
    }

    public String
    type()
    {
        return ExtendsClass.ice_staticId();
    }
}
