// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `myclass.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.sun.ice.demo.myclass;

public class UnsupportException extends BaseException
{
    public UnsupportException()
    {
        super();
        reason = "";
    }

    public UnsupportException(Throwable __cause)
    {
        super(__cause);
        reason = "";
    }

    public UnsupportException(String reason)
    {
        this.reason = reason;
    }

    public UnsupportException(String reason, Throwable __cause)
    {
        super(__cause);
        this.reason = reason;
    }

    public String
    ice_name()
    {
        return "myclass::UnsupportException";
    }

    public String reason;

    protected void
    __writeImpl(IceInternal.BasicStream __os)
    {
        __os.startWriteSlice("::myclass::UnsupportException", -1, false);
        __os.writeString(reason);
        __os.endWriteSlice();
        super.__writeImpl(__os);
    }

    protected void
    __readImpl(IceInternal.BasicStream __is)
    {
        __is.startReadSlice();
        reason = __is.readString();
        __is.endReadSlice();
        super.__readImpl(__is);
    }

    public static final long serialVersionUID = 199817937L;
}
