// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `mymodule.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.sun.ice.demo.mymodule.module01;

public final class ModuleInterfaceHolder extends Ice.ObjectHolderBase<ModuleInterface>
{
    public
    ModuleInterfaceHolder()
    {
    }

    public
    ModuleInterfaceHolder(ModuleInterface value)
    {
        this.value = value;
    }

    public void
    patch(Ice.Object v)
    {
        if(v == null || v instanceof ModuleInterface)
        {
            value = (ModuleInterface)v;
        }
        else
        {
            IceInternal.Ex.throwUOE(type(), v);
        }
    }

    public String
    type()
    {
        return _ModuleInterfaceDisp.ice_staticId();
    }
}
