// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `proxy.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.sun.ice.demo.proxy;

public final class MyInterface3PrxHolder
{
    public
    MyInterface3PrxHolder()
    {
    }

    public
    MyInterface3PrxHolder(MyInterface3Prx value)
    {
        this.value = value;
    }

    public MyInterface3Prx value;
}
